USE DVR_UNIVER;

SELECT FACULTY.FACULTY, PULPIT
	FROM PULPIT
	JOIN FACULTY ON FACULTY.FACULTY = PULPIT.FACULTY
	GROUP BY ROLLUP(FACULTY.FACULTY, PULPIT);

DECLARE @faculty NVARCHAR(20), @pulp NVARCHAR(20), @teachers INT;
DECLARE EX8_Cursor CURSOR LOCAL STATIC
	FOR SELECT FACULTY.FACULTY, PULPIT
	FROM PULPIT
	JOIN FACULTY ON FACULTY.FACULTY = PULPIT.FACULTY
	GROUP BY FACULTY.FACULTY, PULPIT;

OPEN EX8_Cursor;

FETCH EX8_Cursor INTO @faculty, @pulp;

WHILE @@FETCH_STATUS = 0
BEGIN
	PRINT 'Факультет: ' + @faculty;
	PRINT 'Кафедра: ' + @pulp;
	FETCH EX8_Cursor INTO @faculty, @pulp;
END;
CLOSE EX8_Cursor;
