USE DVR_UNIVER;

SELECT FACULTY.FACULTY AS 'Факультет', 
	   PULPIT.PULPIT AS 'Кафедра',
	   PROFESSION.PROFESSION AS 'Специальность',
	   SUBJECT.SUBJECT AS 'Дисциплина',
	   STUDENT.NAME AS 'Имя студента',
CASE
	WHEN (PROGRESS.NOTE = 6) then 'шесть'
	WHEN (PROGRESS.NOTE = 7) then 'семь'
	WHEN (PROGRESS.NOTE = 8) then 'восемь'
END 'Оценка'
FROM PROGRESS
JOIN STUDENT ON STUDENT.IDSTUDENT = PROGRESS.IDSTUDENT AND PROGRESS.NOTE BETWEEN 6 AND 8
JOIN SUBJECT ON SUBJECT.SUBJECT = PROGRESS.SUBJECT
JOIN PULPIT ON PULPIT.PULPIT = SUBJECT.PULPIT
JOIN GROUPS ON GROUPS.IDGROUP = STUDENT.IDGROUP
JOIN FACULTY ON FACULTY.FACULTY = GROUPS.FACULTY
JOIN PROFESSION ON PROFESSION.PROFESSION = GROUPS.PROFESSION
ORDER BY FACULTY.FACULTY, PULPIT.PULPIT, PROFESSION.PROFESSION, STUDENT.NAME ASC, PROGRESS.NOTE DESC;
