USE DVR_MyBase_Test;

-- показать коммутативность
-- объединение LEFT JOIN and RIGHT JOIN
-- включение INNER JOIN
SELECT *
FROM TEACHER FULL OUTER JOIN CURRICULUM
ON CURRICULUM.TEACHER = TEACHER.TEACHER_KEY;

SELECT *
FROM  CURRICULUM FULL OUTER JOIN TEACHER
ON CURRICULUM.TEACHER = TEACHER.TEACHER_KEY;

-- запрос, результат которого содержит данные левой (в операции FULL OUTER JOIN) таблицы 
-- и не содержит данные правой
SELECT *
FROM  TEACHER FULL OUTER JOIN CURRICULUM 
ON CURRICULUM.TEACHER = TEACHER.TEACHER_KEY
WHERE CURRICULUM.CURRICULUM_KEY IS NULL;

-- запрос, результат которого содержит данные правой таблицы и не содержащие данные ле-вой
SELECT *
FROM  CURRICULUM FULL OUTER JOIN TEACHER 
ON CURRICULUM.TEACHER = TEACHER.TEACHER_KEY
WHERE CURRICULUM.CURRICULUM_KEY IS NULL;

-- запрос, результат которого содержит данные правой таблицы и левой таблиц
SELECT *
FROM  CURRICULUM FULL OUTER JOIN TEACHER -- можно было использовать INNER JOIN без WHERE в конце
ON CURRICULUM.TEACHER = TEACHER.TEACHER_KEY
WHERE CURRICULUM.TEACHER IS NOT NULL AND TEACHER.TEACHER_KEY IS NOT NULL;