USE DVR_MyBase_Test;

SELECT *
FROM CURRICULUM
JOIN TEACHER ON CURRICULUM.TEACHER = TEACHER.TEACHER_KEY
ORDER BY
(CASE
	WHEN (HOURS_NUMBERS BETWEEN 150 AND 250) THEN 3
	WHEN (HOURS_NUMBERS BETWEEN 0 AND 150) THEN 2
	ELSE 1
 END);

 SELECT *
 FROM TEACHER
 RIGHT JOIN CURRICULUM ON CURRICULUM.TEACHER = TEACHER.TEACHER_KEY;

 SELECT *
 FROM TEACHER
 FULL JOIN CURRICULUM ON CURRICULUM.TEACHER = TEACHER.TEACHER_KEY;

 SELECT *
 FROM TEACHER
 CROSS JOIN CURRICULUM;

