USE DVR_UNIVER

SELECT TOP(1)
	(SELECT AVG(NOTE) FROM PROGRESS WHERE SUBJECT LIKE 'нюХо')[нюХо],
	(SELECT AVG(NOTE) FROM PROGRESS WHERE SUBJECT LIKE 'йц')[йц],
	(SELECT AVG(NOTE) FROM PROGRESS WHERE SUBJECT LIKE 'ясад')[ясад]
FROM PROGRESS;