USE DVR_UNIVER;

SELECT AUDITORIUM_NAME, AUDITORIUM_TYPE, AUDITORIUM_CAPACITY
FROM AUDITORIUM a
WHERE AUDITORIUM_CAPACITY = (SELECT TOP(1) AUDITORIUM_CAPACITY FROM AUDITORIUM aa
							WHERE aa.AUDITORIUM_TYPE = a.AUDITORIUM_TYPE
							ORDER BY AUDITORIUM_CAPACITY DESC);
